/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  twitch: {
    enabled: boolean;
    clientID: string;
    clientSecret: string;
    redirectURI: string;
    channelName?: string;
    streamTitle: string;
    streamDefaultGame: string;
    ffzIntegration?: boolean;
    ffzUseRepeater?: boolean;
    ffzBlacklist?: string[];
  };
  schedule: {
    defaultURL: string;
    ignoreGamesWhileImporting?: string[];
    disableSpeedrunComLookup: boolean;
    customData?: {
      name: string;
      key: string;
    }[];
  };
}
